RefugioDeAnimales/urls.py
from django.contrib import admin
from django.contrib.auth.views import login, logout_then_login, password_reset, password_reset_confirm, password_reset_done, password_reset_complete
from django.urls import include,path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('mascota/', include('apps.mascota.urls'),name="mascota"),
    path('adopcion/', include('apps.adopcion.urls'),name="adopcion"),
    path('usuario/', include('apps.usuario.urls'),name="usuario"),
    path('accounts/login/',login,kwargs={'template_name': 'index.html'}, name="login"),
    path('',login,kwargs={'template_name': 'index.html'}, name="login"),
    path('logout/',logout_then_login, name="logout"),

    #passwordResetPaths
    path('reset/passwordReset', password_reset, kwargs={'template_name':'passwordReset/passwordResetForm.html','email_template_name': 'passwordReset/passwordResetEmail.html'}, name='password_reset'), 

    path('reset/passwordResetDone', password_reset_done, kwargs={'template_name': 'passwordReset/passwordResetDone.html'}, name='password_reset_done'),

    path('reset/<uidb64>[0-9A-Za-z_\-]/<token>', password_reset_confirm, kwargs={'template_name': 'passwordReset/passwordResetConfirm.html'}, name='password_reset_confirm'),

    path('reset/done', password_reset_complete, kwargs={'template_name': 'passwordReset/passwordResetComplete.html'}, name='password_reset_complete'),
]

apps/adopcion/models.py
from django.db import models

# Create your models here.

class Persona(models.Model):
    nombre = models.CharField(max_length=50)
    apellidos = models.CharField(max_length=70)
    edad = models.IntegerField()
    telefono = models.CharField(max_length=12)
    email = models.EmailField()
    domicilio = models.TextField()
    
    def __str__(self):
        return '{}'.format(self.nombre+" "+self.apellidos)
    
class Solicitud(models.Model):
    persona = models.ForeignKey(Persona, null=True, blank=True,on_delete=models.CASCADE)
    numero_mascotas = models.IntegerField()
    razones = models.TextField()

templates/passwordReset/passwordResetComplete.html
{% extends 'base/base.html' %}

{% block navbar %}
{% endblock %}

{% block content %}

	<h1 class="text-center">Su contraseña se reestableció correctamente</h1>


	<p class="text-center"><a  href="{% url 'login' %}">Iniciar sesión</a></p>

{% endblock %}

templates/passwordReset/passwordResetConfirm.html
{% extends 'base/base.html' %}
{% block navbar %}
{% endblock %}
{% block content %}

{% if validlink %}

<h1>Nueva contraseña</h1>

<form method="post">
{% csrf_token %}

{{ form.new_password1.errors }}
<label for="id_new_password1">Nueva contraseña:</label>
{{ form.new_password1 }}

{{ form.new_password2.errors }}
<label for="id_new_password2">Confirme contraseña:</label>{{ form.new_password2 }}
<input type="submit" value="Cambiar mi contraseña" />
</form>

{% else %}

<h1 class="text-center">ENLACE INVÁLIDO: ESTE ENLACE YA HA SIDO UTILIZADO</h1>

{% endif %}

{% endblock %}

templates/passwordReset/passwordResetDone.html
{% extends 'base/base.html' %}
{% block navbar%}
{% endblock%}
{% block content %}

<h4>Te hemos enviado un correo con un enlace para reestablecer tu contraseña :D</h4>

{% endblock %}

templates/passwordReset/passwordResetEmail.html
Solicitaste reestablecimiento de contraseña.
Click en el siguiente link para crear una nueva contraseña.
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
Tu nombre de usuario es: {{ user.get_username }}

templates/passwordReset/passwordResetForm.html
{% extends 'base/base.html' %}
{% block navbar%}
{% endblock %}
{% block content %}

<p>Recuperar contraseña</p>

<form method="post">
	{% csrf_token %}
	<label for="id_email">Correo:</label> {{ form.email }} 
	<input type="submit" value="Enviar"/>
</form>

{% endblock %}